# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='guest', max_length=50),
        ),
    ]
