# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_goal_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('I', 'Inprogress'), ('C', 'Completed')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='goal',
            name='types',
            field=models.CharField(choices=[('S', 'Small goal'), ('M', 'Medium goal'), ('L', 'Large goal'), ('P', 'Planned goal')], default='S', max_length=1),
        ),
    ]
